### ISSUE TITLE
It's really cool but glitchy

### ISSUE THREAD

**Issue by Valkatastz** [NewWayRP/new_banking#4]
It's cool and looks awesome, well made. However, in same time too glitchy. If you sing out, escape or anything to close it, the mouse is stuck on the screen and you cannot do anything else on it. It counts like you are afk and if you have anti-afk system, it will kick you out from the server.

**Comment by Marechoux** [comment]
I had no problem when I was using it. Everything should always work well, however I don't play to this game anymore and some huge changes could  have be done to FiveM.
Your problems can be caused by another addon. If you find any more precise, fell free to make a PR  or a detailed issue.

Concerning the afk system, it  is not really possible to do a lot from here, you have to modify the addon according to your needs. The problem should be limited, sending a transfer should not take weeks.

**Comment by Certurix** [comment]
Hello, I comment this because I currently have this issue.
When you click on the disconnect button of the Bank Menu, the mouse icon is still here and a script error comes :
`SCRIPT ERROR: @newbanking/server.lua:42: attempt to index a nil value (global 'ESX')`
Can you help me please?

Ah and, sorry for buping this closed issue.
